using System;

namespace SourceGeneratorLib.Extensions
{
    public class SharedMeta
    {
        public static readonly string GeneratedByDataBuilderGeneratorPreamble = @"
// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the data builder generator tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
".Replace("\r\n", "\n").Replace("\n", Environment.NewLine);

    }
}